name: test

on:
  pull_request:
    branches: [ main ]
jobs:
  UnitTests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
    - name: Run tests
      run: ./gradlew :lib:cleanTestDebugUnitTest :lib:testDebugUnitTest --tests "de.contentpass.lib.*"